### ISSUE TITLE
Create Kanban board

### ISSUE THREAD

**Issue by alanluqman** [AckonSamuel/catalog-of-my-things#25]
Dear Review, we are grouped of three (@alanluqman, @AbdollahRaafat, @AckonSamuel) working of this capstone project.
We are creating Main file and Item class in group, then every individual is in charge of specific part of the project which we set in kanban board.

**Project link:**
https://github.com/AckonSamuel/catalog-of-my-things

**Comment by peterrobert** [comment]
Hi,  @alanluqman @AbdollahRaafat  and @AckonSamuel , 


### Highlights!

[ ] Good project set up ✔️
[ ] Descriptive pull request ✔️


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
